---
#eureka:
#  server:
#    enableSelfPreservation: false
#    evictionIntervalTimerInMs: 5000
#    peerNodeConnectionIdleTimeoutSeconds: 5
#    renewalThresholdUpdateIntervalMs: 10000
#    peerEurekaStatusRefreshTimeIntervalMs: 10000
#    peerEurekaNodesUpdateIntervalMs: 10000
#    waitTimeInMsWhenSyncEmpty: 0
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${EUREKA_HOST:eureka.instance.hostname}:${EUREKA_PORT:server.port}/eureka/
#      #      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:nimda}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

spring:
  application:
    name: eureka
#  security:
#    user:
#      name: ${EUREKA_USERNAME:admin}
#      password: ${EUREKA_PASSWORD:nimda}
#    basic:
#      enabled: true
#      path: /**
server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    #    register-with-eureka: false
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://${EUREKA_HOST:eureka.instance.hostname}:${EUREKA_PORT:server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    peer-node-connection-idle-timeout-seconds: 5
    renewal-threshold-update-interval-ms: 10000
    peer-eureka-status-refresh-time-interval-ms: 10000
    peer-eureka-nodes-update-interval-ms: 10000
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost



#
#server:
#  port: 8761
#
#eureka:
#  server:
#    enableSelfPreservation: false #Eureka servers will stop the eviction of all instances if the number of heartbeats renewals is below the expected threshold. The warning in your Eureka servers shows this situation happened
#    evictionIntervalTimerInMs: 5000
#    peerNodeConnectionIdleTimeoutSeconds: 5
#    renewalThresholdUpdateIntervalMs: 10000
#    peerEurekaStatusRefreshTimeIntervalMs: 10000
#    peerEurekaNodesUpdateIntervalMs: 10000
#    waitTimeInMsWhenSyncEmpty: 0
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: true
#    fetchRegistry: false
#    serviceUrl:
<<<<<<< HEAD
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
=======
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
>>>>>>> parent of 4bde575... changed application and eureka config yml
